const detailFixture = {
  id: 20613,
  title: {
    romaji: "Ao Haru Ride",
    english: "Blue Spring Ride",
    native: "アオハライド",
  },
  description:
    "Futaba Yoshioka wants to make a fresh start in high school.<br><br>But when she runs into <i>Kou Mabuchi</i>, a boy she once loved in middle school, old feelings resurface.<br><br>Together they navigate friendship, heartbreak, and growing up.",
  bannerImage: "https://placehold.co/1200x400",
  coverImage: {
    extraLarge: "https://placehold.co/460x650",
    large: "https://placehold.co/460x650",
    color: "#e4a15b",
  },
  format: "TV",
  episodes: 12,
  duration: 24,
  status: "FINISHED",
  season: "SUMMER",
  seasonYear: 2014,
  averageScore: 75,
  popularity: 231842,
  source: "MANGA",
  genres: ["Comedy", "Drama", "Romance", "Shoujo"],
  studios: {
    edges: [
      { isMain: true, node: { id: 11, name: "Production I.G" } },
      { isMain: false, node: { id: 22, name: "Other Studio" } },
    ],
  },
  rankings: [
    {
      id: 1,
      rank: 82,
      type: "RATED",
      format: "TV",
      year: 2014,
      season: "SUMMER",
      allTime: false,
      context: "highest rated summer 2014 anime",
    },
    {
      id: 2,
      rank: 45,
      type: "POPULAR",
      format: "TV",
      year: null,
      season: null,
      allTime: true,
      context: "most popular all time",
    },
    {
      id: 3,
      rank: 120,
      type: "RATED",
      format: "TV",
      year: null,
      season: null,
      allTime: true,
      context: "highest rated all time",
    },
  ],
  tags: [
    { id: 1, name: "Tragedy", rank: 70, isMediaSpoiler: false, isGeneralSpoiler: false, isAdult: false },
    { id: 2, name: "School", rank: 85, isMediaSpoiler: false, isGeneralSpoiler: false, isAdult: false },
    { id: 3, name: "Coming of Age", rank: 80, isMediaSpoiler: false, isGeneralSpoiler: false, isAdult: false },
    { id: 4, name: "Female Protagonist", rank: 90, isMediaSpoiler: false, isGeneralSpoiler: false, isAdult: false },
    { id: 5, name: "Primarily Female Cast", rank: 60, isMediaSpoiler: false, isGeneralSpoiler: false, isAdult: false },
    { id: 6, name: "Love Triangle", rank: 75, isMediaSpoiler: false, isGeneralSpoiler: false, isAdult: false },
    { id: 7, name: "Time Skip", rank: 55, isMediaSpoiler: true, isGeneralSpoiler: false, isAdult: false },
    { id: 8, name: "Character Death", rank: 50, isMediaSpoiler: true, isGeneralSpoiler: true, isAdult: false },
    { id: 9, name: "Tsundere", rank: 65, isMediaSpoiler: false, isGeneralSpoiler: false, isAdult: false },
    { id: 10, name: "Ensemble Cast", rank: 45, isMediaSpoiler: false, isGeneralSpoiler: false, isAdult: false },
    { id: 11, name: "Nudity", rank: 40, isMediaSpoiler: false, isGeneralSpoiler: false, isAdult: true },
    { id: 12, name: "Friendship", rank: 72, isMediaSpoiler: false, isGeneralSpoiler: false, isAdult: false },
  ],
};

export default detailFixture;
